# Generated by Django 4.1.1 on 2022-11-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('id_asig', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asis', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.IntegerField(blank=True, null=True)),
                ('id_jornada', models.IntegerField(blank=True, null=True)),
                ('id_seccion', models.IntegerField(blank=True, null=True)),
                ('asistencia', models.IntegerField()),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=8)),
                ('jornada', models.CharField(max_length=10)),
                ('id_asig', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jornada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=6)),
                ('id_jornada', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=30)),
                ('appaterno', models.CharField(max_length=30)),
                ('apmaterno', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
                ('id_tipo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
