# Generated by Django 4.1.2 on 2022-10-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'asignatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('appaterno', models.CharField(max_length=20)),
                ('apmaterno', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('appaterno', models.CharField(max_length=20)),
                ('apmaterno', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_user',
                'managed': False,
            },
        ),
    ]
